
name: Change notebook

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "**"
  workflow_dispatch:
    
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    # ==================================================
    #              INSTALL DEPENDENCIES
    # ==================================================
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f .github/workflows/requirements.txt ]; then pip install -r .github/workflows/requirements.txt; fi

    # ==================================================
    #          RUN SCRIPT TO CHANGE NOTEBOOK
    # ==================================================
    - name: Run python script that will call on colab
      run: |
        python Chenge_pip_install.py

    # ==================================================
    #                  PUSH CHANGES
    # ==================================================
    - name: Push changes
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Accessing the secret
      run: |
          git config --local user.email "playgroundmr0@gmail.com"
          git config --local user.name "playground-mr0"
          git add .
          git commit -m "Automated commit"
          git push origin $GITHUB_REF
       
