name: notebook colab CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    # ==================================================
    #      RUN PLAYGROUND NOTEBOOKS WITH SELENIUM
    # ==================================================
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: run python script that will call on colab
      run: |
        python seleniumbase_python_tutorial.py
       
