name: notebook colab CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    # ==================================================
    #              INSTALL DEPENDENCIES
    # ==================================================
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f .github/workflows/requirements.txt ]; then pip install -r .github/workflows/requirements.txt; fi

    # ==================================================
    #      RUN PLAYGROUND NOTEBOOKS WITH SELENIUM
    # ==================================================
    - name: Run python script that will call on colab
      run: |
        python seleniumbase_python_tutorial.py

    # ==================================================
    #      MOVE RESULTS TO CORRECT REPO LOCATION
    # ==================================================
    #- name: Move results to correct folder
    #  run: mv downloaded_files/* results/
    #       rm -rf downloaded_files

    # ==================================================
    #                  PUSH CHANGES
    # ==================================================
    - name: Push changes
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Accessing the secret
      run: |
          git config --global user.email "playgroundmr0@gmail.com"
          git config --global user.name "playground-mr0"
          git add .
          git commit -m "Automated commit"
          git push origin main
       
